### ISSUE TITLE
ConvFFTExt::conv_fft is broken with PaddingMode::Circular

### ISSUE THREAD

**Issue by deavid** [TYPEmber/ndarray-conv#3]
PaddingMode::Circular doesn't work with conv_fft.

To check this, just add a new unit test to `src/conv_fft/fft.rs`:

```rust
    #[test]
    fn test_conv_fft_circular() {
        use ndarray::Array1;
        let arr: Array1<f32> =
            array![0.0, 0.1, 0.3, 0.4, 0.0, 0.1, 0.3, 0.4, 0.0, 0.1, 0.3, 0.4, 0.0, 0.1, 0.3, 0.4];
        let kernel: Array1<f32> = array![0.1, 0.3, 0.6, 0.3, 0.1];

        arr.conv_fft(&kernel, crate::ConvMode::Same, crate::PaddingMode::Circular)
            .unwrap();
    }
```

Result:

```
test conv_fft::fft::tests::test_conv_fft_circular ... FAILED

failures:

---- conv_fft::fft::tests::test_conv_fft_circular stdout ----
thread 'conv_fft::fft::tests::test_conv_fft_circular' panicked at /home/deavid/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ndarray-0.15.6/src/impl_methods.rs:1561:9:
assertion failed: self.pointer_is_inbounds()
stack backtrace:
   0: rust_begin_unwind
             at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/std/src/panicking.rs:665:5
   1: core::panicking::panic_fmt
             at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/core/src/panicking.rs:74:14
   2: core::panicking::panic
             at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/core/src/panicking.rs:148:5
   3: ndarray::impl_methods::<impl ndarray::ArrayBase<S,D>>::ensure_unique
             at /home/deavid/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ndarray-0.15.6/src/impl_methods.rs:1561:9
   4: ndarray::impl_methods::<impl ndarray::ArrayBase<S,D>>::view_mut
             at /home/deavid/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ndarray-0.15.6/src/impl_methods.rs:159:9
   5: ndarray::impl_methods::<impl ndarray::ArrayBase<S,D>>::index_axis_mut
             at /home/deavid/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ndarray-0.15.6/src/impl_methods.rs:972:9
   6: ndarray_conv::padding::half_dim::circular_back
             at ./src/padding/half_dim.rs:338:13
   7: ndarray_conv::padding::dim::circular
             at ./src/padding/dim.rs:156:5
   8: ndarray_conv::padding::padding_circular::{{closure}}
             at ./src/padding/mod.rs:321:13
   9: core::iter::traits::iterator::Iterator::for_each::call::{{closure}}
             at /home/deavid/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/traits/iterator.rs:810:29
  10: <core::iter::adapters::enumerate::Enumerate<I> as core::iter::traits::iterator::Iterator>::fold::enumerate::{{closure}}
             at /home/deavid/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/adapters/enumerate.rs:107:27
  11: <core::slice::iter::Iter<T> as core::iter::traits::iterator::Iterator>::fold
             at /home/deavid/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/slice/iter/macros.rs:232:27
  12: <core::iter::adapters::enumerate::Enumerate<I> as core::iter::traits::iterator::Iterator>::fold
             at /home/deavid/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/adapters/enumerate.rs:113:9
  13: core::iter::traits::iterator::Iterator::for_each
             at /home/deavid/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/traits/iterator.rs:813:9
  14: ndarray_conv::padding::padding_circular
             at ./src/padding/mod.rs:317:5
  15: <ndarray::ArrayBase<S,D> as ndarray_conv::padding::PaddingExt<_,T,ndarray::ArrayBase<ndarray::data_repr::OwnedRepr<T>,ndarray::dimension::dim::Dim<[usize; N]>>>>::padding_in
             at ./src/padding/mod.rs:146:38
  16: ndarray_conv::conv_fft::padding::data
             at ./src/conv_fft/padding.rs:61:5
  17: <ndarray::ArrayBase<S,ndarray::dimension::dim::Dim<[usize; N]>> as ndarray_conv::conv_fft::ConvFFTExt<T,S,SK,_>>::conv_fft_with_processor
             at ./src/conv_fft/mod.rs:253:27
  18: <ndarray::ArrayBase<S,ndarray::dimension::dim::Dim<[usize; N]>> as ndarray_conv::conv_fft::ConvFFTExt<T,S,SK,_>>::conv_fft
             at ./src/conv_fft/mod.rs:213:9
  19: ndarray_conv::conv_fft::fft::tests::test_conv_fft_circular
             at ./src/conv_fft/fft.rs:433:9
  20: ndarray_conv::conv_fft::fft::tests::test_conv_fft_circular::{{closure}}
             at ./src/conv_fft/fft.rs:427:32
  21: core::ops::function::FnOnce::call_once
             at /home/deavid/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:250:5
  22: core::ops::function::FnOnce::call_once
             at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

```

The other padding modes seem to work, and Circular seems to work with the regular ConvExt trait.

**Comment by TYPEmber** [comment]
Thank you very much for helping to test this issue. I have identified the cause of the problem, which was due to not using a generic type during an unsafe type cast. I will update to a new version as soon as possible.

```rust
// let output_mut = (buffer as *const _ as *mut Array<T, Dim<[Ix; N]>>).as_mut().unwrap();
let output_mut = (buffer as *const _ as *mut ArrayBase<S, DO>).as_mut().unwrap();
```
